### ISSUE TITLE
Roadmap v1.0.0

### ISSUE THREAD

**Issue by fzumstein** [ZoomerAnalytics/xlwings#324]
This is only an overview, the individual steps are/should be logged in separate issues (links will follow).  

- [ ] Mac Excel 2016 RunPython calls
- [ ] Accessors (nparray, dataframe, ...)
- [ ] Runtime add-in as alternative to VBA module incl. version check between VBA and Python
- [ ] Handle the potential EXCEL.EXE zombie processes when using global App/Workbook vars
- [ ] API refactoring
- [ ] xlwings Exceptions

**Comment by a093130** [comment]
I try to access named ranges and named sheets from the xlwings python API.  No guarantee the workbook opened will be in the format I require.  So looking for exceptions.
example:
    try:
        wb = xw.Book(fname)
        sht = wb.sheets('GMAT')
        return sht.range('A1').expand().value
    except com_error:
        logging.error('Could not access range on workbook sheet GMAT.')        

I think xlwings is throwing an exception called com_error when the sheetname is bad, but python does not recognize it.  Example:

ohno = cfs.sheeterror(fname[0])
Traceback (most recent call last):

  File "<ipython-input-161-3818aba80da5>", line 1, in <module>
    ohno = cfs.sheeterror(fname[0])

  File "C:\Users\chelm\Documents\WorkingFolder\ProjectRoot\projects\Python3\GMAT-Automation\fromconfigsheet.py", line 74, in sheeterror
    sht = wb.sheets('bad')

  File "C:\Users\chelm\Anaconda3\Lib\site-packages\xlwings\main.py", line 2783, in __call__
    return Sheet(impl=self.impl(name_or_index))

  File "C:\Users\chelm\Anaconda3\Lib\site-packages\xlwings\_xlwindows.py", line 511, in __call__
    return Sheet(xl=self.xl(name_or_index))

  File "C:\Users\chelm\Anaconda3\Lib\site-packages\xlwings\_xlwindows.py", line 151, in __call__
    v = self._inner(*args, **kwargs)

  File "C:\Users\chelm\Anaconda3\Lib\site-packages\win32com\client\dynamic.py", line 197, in __call__
    return self._get_good_object_(self._oleobj_.Invoke(*allArgs),self._olerepr_.defaultDispatchName,None)

com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147352565), None)


Xlwings documentation should tell users what exceptions are being thrown, and the exception class should be made available for catch in the module definition.  If there are no exceptions for non-existent sheets, ranges, or other named Excel objects, please consider adding specific exceptions for these.
